export {default as Login} from './login';
export { default as Home} from './home';
export {default as ProductDetail} from './productDetail';
export {default as Genres} from './genres';
export {default as Payment} from './payment';
export {default as CreateProduct} from './createProduct';
export {default as UpdateProduct} from './updateProduct';
export {default as FilterProduct} from './filterProduct';
export {default as PaymentSuccess} from './paymentSuccess';
export {default as UserManagement} from './userManagement';
export {default as StaffManagement} from './staffManagement';
export {default as Personal} from './personal';
export {default as PurchaseHistory} from './purchaseHistory';
export {default as PurchaseHistoryDetail} from './purchaseHistoryDetail';